server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: agro-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/fincas/**,/api/cultivos/**,/api/parcelas/**,/api/dashboard/**,/api/alertas/**,/api/parametros/**,/api/reportes/**,/api/recomendaciones/**,/api/sincronizacion/**
